name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build next
        run: yarn build
      
      - name: Export static
        run: yarn export

      - name: Run deploy script
        run: |
          git config user.name "Linn Dahlgren" && git config user.email "admin@opposite.biz"
          npm run gh-pages-deploy